# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30, verbose_name=b'Nom de famille')),
                ('firstname', models.CharField(max_length=30, verbose_name=b'Pr\xc3\xa9nom(s)')),
                ('sex', models.CharField(choices=[(b'Masculin', b'Masculin'), (b'Feminin', b'Feminin')], max_length=8, verbose_name=b'Sexe')),
                ('birthday', models.DateField(verbose_name=b'Date de naissance')),
                ('birthhour', models.TimeField(null=True, verbose_name=b'Heure de naissance')),
                ('birthcity', models.CharField(max_length=30, verbose_name=b'Ville de naissance')),
                ('birthcountry', django_countries.fields.CountryField(max_length=2, verbose_name=b'Pays de naissance')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fk_parent1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_Parent1', to='Identity.Identity', verbose_name=b'ID parent1')),
                ('fk_parent2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_Parent2', to='Identity.Identity', verbose_name=b'ID parent2')),
            ],
        ),
    ]
