# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_number', models.CharField(max_length=30, null=True, unique=True, verbose_name=b'numero social')),
                ('title', models.CharField(choices=[(b'Mr', b'Monsieur'), (b'Mlle', b'Mademoiselle'), (b'Mme', b'Madame'), (b'Dr', b'Docteur'), (b'Me', b'Ma\xc3\xaetre')], max_length=12, verbose_name=b'Civilit\xc3\xa9')),
                ('young_girl_lastname', models.CharField(blank=True, max_length=30, verbose_name=b'Nom de jeune fille')),
                ('lastname', models.CharField(max_length=30, verbose_name=b'Nom de famille')),
                ('firstname', models.CharField(max_length=30, verbose_name=b'Pr\xc3\xa9nom(s)')),
                ('sex', models.CharField(choices=[(b'Masculin', b'Masculin'), (b'F\xc3\xa9minin', b'F\xc3\xa9minin')], max_length=8, verbose_name=b'Sexe')),
                ('status', models.CharField(choices=[(b'C\xc3\xa9libataire', b'C\xc3\xa9libataire'), (b'Mari\xc3\xa9(e)', b'Mari\xc3\xa9(e)'), (b'Divorc\xc3\xa9(e)', b'Divorc\xc3\xa9(e)'), (b'Veuf/Veuve', b'Veuf/Veuve')], max_length=15, verbose_name=b'Statut civil')),
                ('birthday', models.DateField(verbose_name=b'Date de naissance')),
                ('birthcity', models.CharField(max_length=30, verbose_name=b'Ville de naissance')),
                ('birthcountry', django_countries.fields.CountryField(max_length=2, verbose_name=b'Pays de naissance')),
                ('birthmairie', models.CharField(max_length=30, verbose_name=b'Mairie de naissance')),
                ('nationality', models.CharField(max_length=30, verbose_name=b'Nationalit\xc3\xa9')),
                ('job', models.CharField(max_length=30, verbose_name=b'Profession')),
                ('adress', models.CharField(max_length=30, verbose_name=b'Adresse')),
                ('city', models.CharField(max_length=30, verbose_name=b'Ville')),
                ('zip', models.IntegerField(verbose_name=b'Code Postal')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name=b'Pays')),
                ('mail', models.CharField(blank=True, max_length=30, verbose_name=b'Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name=b'T\xc3\xa9l\xc3\xa9phone')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mairie', models.CharField(default=b' ', max_length=30, verbose_name=b'Mairie')),
            ],
        ),
    ]
