# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='InformationsInstitution',
            field=models.CharField(default=b'', max_length=30, verbose_name=b'Informations Institution'),
        ),
    ]
