# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='young_girl_lastname',
            field=models.CharField(blank=True, max_length=30, verbose_name=b'Nom de jeune fille'),
        ),
    ]
