# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationsInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(choices=[(b'Mairie', b'Mairie'), ('Pr\xe9fecture', b'Pr\xc3\xa9fecture'), (b'Douane', b'Douane'), ('Imp\xf4ts', 'Imp\xf4ts'), (b'Autre', b'Autre')], max_length=30, verbose_name=b"Type d'institution")),
                ('Adresse', models.CharField(max_length=30, verbose_name=b'Adresse')),
                ('Zip', models.IntegerField(verbose_name=b'Code Postal')),
                ('Ville', models.CharField(max_length=30, verbose_name=b'Ville')),
                ('Pays', django_countries.fields.CountryField(max_length=2, verbose_name=b'Pays')),
                ('Region', models.CharField(max_length=30, verbose_name=b'R\xc3\xa9gion')),
                ('TelephoneFixe', models.CharField(max_length=30, verbose_name=b'T\xc3\xa9l\xc3\xa9phone Fixe')),
                ('Fax', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Fax')),
                ('Email', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Email')),
            ],
        ),
    ]
