# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation_Recensement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(b'Mr', b'Monsieur'), (b'Mlle', b'Mademoiselle'), (b'Mme', b'Madame'), (b'Dr', b'Docteur'), (b'Me', b'Ma\xc3\xaetre')], max_length=12, verbose_name=b'Civilit\xc3\xa9')),
                ('lastname', models.CharField(max_length=30, verbose_name=b'Nom de famille')),
                ('firstname', models.CharField(max_length=30, verbose_name=b'Pr\xc3\xa9nom(s)')),
                ('sex', models.CharField(choices=[(b'Masculin', b'Masculin'), (b'Feminin', b'Feminin')], max_length=8, verbose_name=b'Sexe')),
                ('birthday', models.DateField(verbose_name=b'Date de naissance')),
                ('birthcity', models.CharField(max_length=30, verbose_name=b'Ville de naissance')),
                ('birthcountry', django_countries.fields.CountryField(max_length=2, verbose_name=b'Pays de naissance')),
                ('city', models.CharField(max_length=30, verbose_name=b'Ville')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name=b'Pays')),
                ('mairie', models.CharField(default=b' ', max_length=30, verbose_name=b'Mairie')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
