# -*- coding: utf-8 -*-

"""
Django settings for DatasystemsCORE project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
http://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
http://docs.djangoproject.com/en/1.10/ref/settings/
"""
from django.conf import global_settings
import os
import Global_variables

from django.contrib.messages import constants as message_constants
MESSAGE_LEVEL = message_constants.DEBUG

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Global_variables.SECRET_KEY


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = Global_variables.ALLOWED_HOSTS

DATE_INPUT_FORMATS = ('%d-%m-%Y')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'Django_Cache',
    }
}


# Application definition

INSTALLED_APPS = [
    'Informations',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrapform',
    'django_countries',
    'debug_toolbar',
    'chartit',
    'Configurations',
    'Accueil',
    'log',
    'Identity',
    'rest_framework',
]


MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'DatasystemsCORE.middleware.OnlineNowMiddleware',
]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]

ROOT_URLCONF = 'DatasystemsCORE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates',
                'Accueil/templates/',
                "Identity/templates",
                "Informations/templates",
                "log/templates",
                "Configurations/templates",
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug' : DEBUG,
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Accueil.context_processors.GetTheme',
                'Accueil.context_processors.Test',
                'Accueil.context_processors.get_infos',
                'Configurations.context_processors.GetTheme',
                'Identity.context_processors.GetTheme',
                'log.context_processors.GetTheme',
                'Informations.context_processors.GetTheme',],

            'libraries':{
            'variables': 'DatasystemsCORE.templatetags.variables',

            }
        },
    },
]

WSGI_APPLICATION = 'DatasystemsCORE.wsgi.application'


# Database
# http://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = Global_variables.DATABASES

BDD = ('default', 'DS_Douane', 'DS_Impots', 'DS_Finance')

DATABASE_ROUTERS = ['DatasystemsCORE.routersLocal.LocalRouter', 'DatasystemsCORE.routersGlobal.GlobalRouter']
# DATABASE_ROUTERS = ['BirthCertificate.routerBirthCertificate.BirthCertificateRouter']


LOGGING = {

    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
    'require_debug_false': {
         '()': 'django.utils.log.RequireDebugFalse'
    },
    'formatters': {
    'standard': {
        'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
        'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'mail_admins': {
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler' 
            },
        'logfile': {
            'level': 'DEBUG',
            'filename': os.path.join(BASE_DIR, "/Log/info.log")
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'WARN',
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True
        },
        'xhtml2pdf': {
            'handlers': ['logfile'],
            'level': 'DEBUG'
       }
    },
    'applogfile': {
        'level':'DEBUG',
        'class':'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(BASE_DIR, "APPNAME.log"),
        'maxBytes': 1024*1024*15, # 15MB
        'backupCount': 10,
    },
   }
}
    

# Password validation
# http://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# http://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# http://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
THEME_DIRS = os.path.join(BASE_DIR, "static", "Theme/")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), THEME_DIRS, ]

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join('/Users/valentinjungbluth/Desktop/Django/DatasystemsCORE', 'Media/')

LOGIN_URL = '/Home/login/'

# SESSION AGE 5 Minutes
SESSION_COOKIE_AGE = 100*60 # X * 60s

# Simple Math
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'

INTERNAL_IPS = ('127.0.0.1',)

