"""
Django settings for Etat_civil project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
from django.conf import global_settings
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIRS = (
        os.path.join(BASE_DIR, 'templates'),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DATE_INPUT_FORMATS = ('%d-%m-%Y')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'Django_Cache',
    }
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'BirthCertificate',
    'Identity',
    'bootstrapform',
    'Accueil',
    'django_countries',
    'log',
    'Mairie',
    'Table',
    'Recensement',
    'Configurations',
    'debug_toolbar',
    
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]

ROOT_URLCONF = 'Etat_civil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/Users/valentinjungbluth/Desktop/Django/Etat_civil/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/Accueil/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/BirthCertificate/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/Identity/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/Configurations/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/log/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/Mairie/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/Recensement/templates/',
                 '/Users/valentinjungbluth/Desktop/Django/Etat_civil/Table/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug' : DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Accueil.context_processors.GetTheme',
                'BirthCertificate.context_processors.GetTheme',
                'Configurations.context_processors.GetTheme',
                'Identity.context_processors.GetTheme',
                'log.context_processors.GetTheme',
                'Mairie.context_processors.GetTheme',
                'Recensement.context_processors.GetTheme',
                'Table.context_processors.GetTheme',],
        },
    },
]

WSGI_APPLICATION = 'Etat_civil.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases



LOGGING = {

    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
    'require_debug_false': {
         '()': 'django.utils.log.RequireDebugFalse'
    },
    'formatters': {
    'standard': {
        'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
        'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'mail_admins': {
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler' 
            },
        'logfile': {
            'level': 'DEBUG',
            'filename': BASE_DIR + "/Log/info.log"
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'WARN',
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True
        },
        'xhtml2pdf': {
            'handlers': ['logfile'],
            'level': 'DEBUG'
       }
    },
    'applogfile': {
        'level':'DEBUG',
        'class':'logging.handlers.RotatingFileHandler',
        'filename': os.path.join('/Users/valentinjungbluth/Desktop/APPNAME.log'),
        'maxBytes': 1024*1024*15, # 15MB
        'backupCount': 10,
    },
   }
}
    

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "/Users/valentinjungbluth/Desktop/Django/Etat_civil/static/Theme/"),)

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

LOGIN_URL = '/Home/login/'

# SESSION AGE 5 Minutes
SESSION_COOKIE_AGE = 100*60 # X * 60s

# Simple Math
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'

INTERNAL_IPS = ('127.0.0.1',)
